repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [ --max-line-length=88 ]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#      - id: mypy
#        additional_dependencies: [ mypy==0.910, types-six ]
#        args:
#          - --warn-redundant-casts
#          - --no-implicit-optional
#          - --ignore-missing-imports
#          - --strict-optional
