"""cascade deleting

Revision ID: 17cadbfa43b7
Revises: 3eb2f5bfddc2
Create Date: 2023-08-21 18:37:26.008261

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "17cadbfa43b7"
down_revision = "3eb2f5bfddc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
