"""first

Revision ID: 19eefc2bd7d6
Revises:
Create Date: 2023-08-11 10:07:48.886179

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19eefc2bd7d6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("Username", sa.String(length=60), nullable=False),
        sa.Column("Email", sa.String(), nullable=False),
        sa.Column("Password", sa.String(), nullable=False),
        sa.Column("Is_active", sa.Boolean(), nullable=True),
        sa.Column("User role", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("Created at", sa.TIMESTAMP(), nullable=True),
        sa.Column("Updated at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("Email"),
        sa.UniqueConstraint("Username"),
    )
    op.create_table(
        "todo_lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("Name", sa.String(length=100), nullable=False),
        sa.Column("Description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("Created at", sa.TIMESTAMP(), nullable=True),
        sa.Column("Updated at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("Task id", sa.UUID(), nullable=False),
        sa.Column("Name", sa.String(length=100), nullable=False),
        sa.Column("Description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("IN_PROGRESS", "DONE", name="taskstatus"), nullable=True
        ),
        sa.Column("todo_list_id", sa.UUID(), nullable=False),
        sa.Column("Created at", sa.TIMESTAMP(), nullable=True),
        sa.Column("Updated at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["todo_list_id"],
            ["todo_lists.id"],
        ),
        sa.PrimaryKeyConstraint("Task id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("todo_lists")
    op.drop_table("users")
    # ### end Alembic commands ###
