"""user_role

Revision ID: 491645b98269
Revises: 19eefc2bd7d6
Create Date: 2023-08-16 09:15:08.058290

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "491645b98269"
down_revision = "19eefc2bd7d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
