"""second

Revision ID: 852570bd048a
Revises: f3f5a54dadbc
Create Date: 2023-08-07 10:58:15.850725

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "852570bd048a"
down_revision = "f3f5a54dadbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
