"""user_role

Revision ID: 8553ac6e402d
Revises: ec182ccd4f61
Create Date: 2023-08-08 13:46:52.055203

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8553ac6e402d"
down_revision = "ec182ccd4f61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("User role", postgresql.ARRAY(sa.String()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "User role")
    # ### end Alembic commands ###
