"""cascade deleting

Revision ID: d822727777ba
Revises: 17cadbfa43b7
Create Date: 2023-08-21 18:39:39.330840

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d822727777ba"
down_revision = "17cadbfa43b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
