"""cascade deleting.v2

Revision ID: ebcf48042c4c
Revises: d822727777ba
Create Date: 2023-08-21 19:39:51.513859

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ebcf48042c4c"
down_revision = "d822727777ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
