"""third

Revision ID: ec182ccd4f61
Revises: 852570bd048a
Create Date: 2023-08-07 11:00:27.878263

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ec182ccd4f61"
down_revision = "852570bd048a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
